services:
  scraper:
    build: .
    container_name: trustpilot-scraper
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - db
  db:
    image: mysql:8.0
    container_name: trustpilot-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: trustpilot_scraper
      MYSQL_USER: scraper
      MYSQL_PASSWORD: scraper
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: trustpilot-phpmyadmin
    restart: always
    environment:
      PMA_HOST: db
      PMA_USER: scraper
      PMA_PASSWORD: scraper
    ports:
      - "8080:80"
    depends_on:
      - db

volumes:
  db_data: